/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTecnicosRouteImport } from './routes/_authenticated/tecnicos'
import { Route as AuthenticatedRotasRouteImport } from './routes/_authenticated/rotas'
import { Route as AuthenticatedRotaRouteImport } from './routes/_authenticated/rota'
import { Route as AuthenticatedRendimentoRouteImport } from './routes/_authenticated/rendimento'
import { Route as AuthenticatedReducaoRouteImport } from './routes/_authenticated/reducao'
import { Route as AuthenticatedPreventivasRouteImport } from './routes/_authenticated/preventivas'
import { Route as AuthenticatedPermissoesRouteImport } from './routes/_authenticated/permissoes'
import { Route as AuthenticatedPecasRouteImport } from './routes/_authenticated/pecas'
import { Route as AuthenticatedOsRouteImport } from './routes/_authenticated/os'
import { Route as AuthenticatedModelosRouteImport } from './routes/_authenticated/modelos'
import { Route as AuthenticatedEquipamentosRouteImport } from './routes/_authenticated/equipamentos'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated/entregas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConferenciaRouteImport } from './routes/_authenticated/conferencia'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedEquipamentosIdHistoricoRouteImport } from './routes/_authenticated/equipamentos.$id.historico'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTecnicosRoute = AuthenticatedTecnicosRouteImport.update({
  id: '/tecnicos',
  path: '/tecnicos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRotasRoute = AuthenticatedRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRotaRoute = AuthenticatedRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRendimentoRoute = AuthenticatedRendimentoRouteImport.update({
  id: '/rendimento',
  path: '/rendimento',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReducaoRoute = AuthenticatedReducaoRouteImport.update({
  id: '/reducao',
  path: '/reducao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreventivasRoute =
  AuthenticatedPreventivasRouteImport.update({
    id: '/preventivas',
    path: '/preventivas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPermissoesRoute = AuthenticatedPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPecasRoute = AuthenticatedPecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOsRoute = AuthenticatedOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelosRoute = AuthenticatedModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipamentosRoute =
  AuthenticatedEquipamentosRouteImport.update({
    id: '/equipamentos',
    path: '/equipamentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConferenciaRoute =
  AuthenticatedConferenciaRouteImport.update({
    id: '/conferencia',
    path: '/conferencia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipamentosIdHistoricoRoute =
  AuthenticatedEquipamentosIdHistoricoRouteImport.update({
    id: '/$id/historico',
    path: '/$id/historico',
    getParentRoute: () => AuthenticatedEquipamentosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/conferencia': typeof AuthenticatedConferenciaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/equipamentos': typeof AuthenticatedEquipamentosRouteWithChildren
  '/modelos': typeof AuthenticatedModelosRoute
  '/os': typeof AuthenticatedOsRoute
  '/pecas': typeof AuthenticatedPecasRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/preventivas': typeof AuthenticatedPreventivasRoute
  '/reducao': typeof AuthenticatedReducaoRoute
  '/rendimento': typeof AuthenticatedRendimentoRoute
  '/rota': typeof AuthenticatedRotaRoute
  '/rotas': typeof AuthenticatedRotasRoute
  '/tecnicos': typeof AuthenticatedTecnicosRoute
  '/equipamentos/$id/historico': typeof AuthenticatedEquipamentosIdHistoricoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/conferencia': typeof AuthenticatedConferenciaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/equipamentos': typeof AuthenticatedEquipamentosRouteWithChildren
  '/modelos': typeof AuthenticatedModelosRoute
  '/os': typeof AuthenticatedOsRoute
  '/pecas': typeof AuthenticatedPecasRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/preventivas': typeof AuthenticatedPreventivasRoute
  '/reducao': typeof AuthenticatedReducaoRoute
  '/rendimento': typeof AuthenticatedRendimentoRoute
  '/rota': typeof AuthenticatedRotaRoute
  '/rotas': typeof AuthenticatedRotasRoute
  '/tecnicos': typeof AuthenticatedTecnicosRoute
  '/equipamentos/$id/historico': typeof AuthenticatedEquipamentosIdHistoricoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/conferencia': typeof AuthenticatedConferenciaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/equipamentos': typeof AuthenticatedEquipamentosRouteWithChildren
  '/_authenticated/modelos': typeof AuthenticatedModelosRoute
  '/_authenticated/os': typeof AuthenticatedOsRoute
  '/_authenticated/pecas': typeof AuthenticatedPecasRoute
  '/_authenticated/permissoes': typeof AuthenticatedPermissoesRoute
  '/_authenticated/preventivas': typeof AuthenticatedPreventivasRoute
  '/_authenticated/reducao': typeof AuthenticatedReducaoRoute
  '/_authenticated/rendimento': typeof AuthenticatedRendimentoRoute
  '/_authenticated/rota': typeof AuthenticatedRotaRoute
  '/_authenticated/rotas': typeof AuthenticatedRotasRoute
  '/_authenticated/tecnicos': typeof AuthenticatedTecnicosRoute
  '/_authenticated/equipamentos/$id/historico': typeof AuthenticatedEquipamentosIdHistoricoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/clientes'
    | '/conferencia'
    | '/dashboard'
    | '/entregas'
    | '/equipamentos'
    | '/modelos'
    | '/os'
    | '/pecas'
    | '/permissoes'
    | '/preventivas'
    | '/reducao'
    | '/rendimento'
    | '/rota'
    | '/rotas'
    | '/tecnicos'
    | '/equipamentos/$id/historico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/clientes'
    | '/conferencia'
    | '/dashboard'
    | '/entregas'
    | '/equipamentos'
    | '/modelos'
    | '/os'
    | '/pecas'
    | '/permissoes'
    | '/preventivas'
    | '/reducao'
    | '/rendimento'
    | '/rota'
    | '/rotas'
    | '/tecnicos'
    | '/equipamentos/$id/historico'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/clientes'
    | '/_authenticated/conferencia'
    | '/_authenticated/dashboard'
    | '/_authenticated/entregas'
    | '/_authenticated/equipamentos'
    | '/_authenticated/modelos'
    | '/_authenticated/os'
    | '/_authenticated/pecas'
    | '/_authenticated/permissoes'
    | '/_authenticated/preventivas'
    | '/_authenticated/reducao'
    | '/_authenticated/rendimento'
    | '/_authenticated/rota'
    | '/_authenticated/rotas'
    | '/_authenticated/tecnicos'
    | '/_authenticated/equipamentos/$id/historico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tecnicos': {
      id: '/_authenticated/tecnicos'
      path: '/tecnicos'
      fullPath: '/tecnicos'
      preLoaderRoute: typeof AuthenticatedTecnicosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rotas': {
      id: '/_authenticated/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof AuthenticatedRotasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rota': {
      id: '/_authenticated/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof AuthenticatedRotaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rendimento': {
      id: '/_authenticated/rendimento'
      path: '/rendimento'
      fullPath: '/rendimento'
      preLoaderRoute: typeof AuthenticatedRendimentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reducao': {
      id: '/_authenticated/reducao'
      path: '/reducao'
      fullPath: '/reducao'
      preLoaderRoute: typeof AuthenticatedReducaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preventivas': {
      id: '/_authenticated/preventivas'
      path: '/preventivas'
      fullPath: '/preventivas'
      preLoaderRoute: typeof AuthenticatedPreventivasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permissoes': {
      id: '/_authenticated/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof AuthenticatedPermissoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pecas': {
      id: '/_authenticated/pecas'
      path: '/pecas'
      fullPath: '/pecas'
      preLoaderRoute: typeof AuthenticatedPecasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/os': {
      id: '/_authenticated/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof AuthenticatedOsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/modelos': {
      id: '/_authenticated/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof AuthenticatedModelosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipamentos': {
      id: '/_authenticated/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof AuthenticatedEquipamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conferencia': {
      id: '/_authenticated/conferencia'
      path: '/conferencia'
      fullPath: '/conferencia'
      preLoaderRoute: typeof AuthenticatedConferenciaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipamentos/$id/historico': {
      id: '/_authenticated/equipamentos/$id/historico'
      path: '/$id/historico'
      fullPath: '/equipamentos/$id/historico'
      preLoaderRoute: typeof AuthenticatedEquipamentosIdHistoricoRouteImport
      parentRoute: typeof AuthenticatedEquipamentosRoute
    }
  }
}

interface AuthenticatedEquipamentosRouteChildren {
  AuthenticatedEquipamentosIdHistoricoRoute: typeof AuthenticatedEquipamentosIdHistoricoRoute
}

const AuthenticatedEquipamentosRouteChildren: AuthenticatedEquipamentosRouteChildren =
  {
    AuthenticatedEquipamentosIdHistoricoRoute:
      AuthenticatedEquipamentosIdHistoricoRoute,
  }

const AuthenticatedEquipamentosRouteWithChildren =
  AuthenticatedEquipamentosRoute._addFileChildren(
    AuthenticatedEquipamentosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConferenciaRoute: typeof AuthenticatedConferenciaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedEquipamentosRoute: typeof AuthenticatedEquipamentosRouteWithChildren
  AuthenticatedModelosRoute: typeof AuthenticatedModelosRoute
  AuthenticatedOsRoute: typeof AuthenticatedOsRoute
  AuthenticatedPecasRoute: typeof AuthenticatedPecasRoute
  AuthenticatedPermissoesRoute: typeof AuthenticatedPermissoesRoute
  AuthenticatedPreventivasRoute: typeof AuthenticatedPreventivasRoute
  AuthenticatedReducaoRoute: typeof AuthenticatedReducaoRoute
  AuthenticatedRendimentoRoute: typeof AuthenticatedRendimentoRoute
  AuthenticatedRotaRoute: typeof AuthenticatedRotaRoute
  AuthenticatedRotasRoute: typeof AuthenticatedRotasRoute
  AuthenticatedTecnicosRoute: typeof AuthenticatedTecnicosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConferenciaRoute: AuthenticatedConferenciaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedEquipamentosRoute: AuthenticatedEquipamentosRouteWithChildren,
  AuthenticatedModelosRoute: AuthenticatedModelosRoute,
  AuthenticatedOsRoute: AuthenticatedOsRoute,
  AuthenticatedPecasRoute: AuthenticatedPecasRoute,
  AuthenticatedPermissoesRoute: AuthenticatedPermissoesRoute,
  AuthenticatedPreventivasRoute: AuthenticatedPreventivasRoute,
  AuthenticatedReducaoRoute: AuthenticatedReducaoRoute,
  AuthenticatedRendimentoRoute: AuthenticatedRendimentoRoute,
  AuthenticatedRotaRoute: AuthenticatedRotaRoute,
  AuthenticatedRotasRoute: AuthenticatedRotasRoute,
  AuthenticatedTecnicosRoute: AuthenticatedTecnicosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
